### ISSUE TITLE
Feature: Footer GH and LinkedIn Links

### ISSUE THREAD

**Issue by ivonne-hernandez** [isleofyou/lemon-aide#21]
- [ ] As a user, when I scroll all the way down I should see a footer that shows the names of all the contributors and links to their GH and LinkedIn profiles via each site's logo.

- [ ] We will also need to test this functionality.

I created a custom octocat on https://myoctocat.com/build-your-octocat/...it didn't actually email me what I built but I took a screenshot and then went to https://www.remove.bg/ to remove the white background. 
<img width="224" alt="Ivonne-octocat" src="https://user-images.githubusercontent.com/86989161/148965500-d32ac838-fb46-4103-8e2d-cf6e2ad9d45d.png">

![image](https://user-images.githubusercontent.com/86989161/148955122-682d1c05-8a8f-480b-aab3-9eb5b8f57ba5.png)

![image](https://user-images.githubusercontent.com/86989161/148958120-1598447c-c91a-4811-90fe-fa01b5b304ef.png)

![image](https://user-images.githubusercontent.com/86989161/148955352-511daea1-87d7-4956-a843-dff2e79a203a.png)

**Comment by isleofyou** [comment]
Donezo
