### ISSUE TITLE
Feature: Error Handling Component

### ISSUE THREAD

**Issue by ivonne-hernandez** [isleofyou/lemon-aide#4]
As a user, when I visit the homepage and am not able to see any of the products or content I should see an Error message (Component) with the attached picture describing why (Whoops! /n Error: (error msg from state property in App.js)).

![dizzy-robot](https://user-images.githubusercontent.com/86989161/148650148-8d926d00-5abf-46a4-8de2-4dcc3bd8919d.png)
.

**Comment by Markus-Xavier** [comment]
![Screen Shot 2022-01-08 at 2 49 13 PM](https://user-images.githubusercontent.com/48008726/148659554-a3572bee-74ab-429e-874f-5482c0f39ca2.png)

**Comment by ivonne-hernandez** [comment]
This component has now been created, so this issue will be closed.
