### ISSUE TITLE
Feature: Loading Component

### ISSUE THREAD

**Issue by ivonne-hernandez** [isleofyou/lemon-aide#6]
As a user, when I first visit the homepage and do not see any of the products in the products container (or see them loading slowly) I should see a loading icon that rotates in the products container until the fetch Promise for all products has resolved (component mounts) and renders the products in the container. 

![001-loading](https://user-images.githubusercontent.com/86989161/148650464-ac3888c1-88ae-49b5-9bcb-eaa8ee222c91.png)

**Comment by Markus-Xavier** [comment]
![lemonaide spinny 2 0](https://user-images.githubusercontent.com/48008726/148657071-2dd94b43-0cae-4851-90f5-cc77c590a79d.gif)

**Comment by isleofyou** [comment]
Branch merged to main, issue will now be closed. Thanks Markus.
